name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn ci
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
        env:
          CI: true
      - name: Build
        run: yarn run build
